# Generated by Django 4.2.1 on 2023-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_letter_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
