# Generated by Django 4.2.1 on 2023-06-09 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_letter_first_name_letter_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='date_to_send',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
