# Generated by Django 4.2.1 on 2023-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_letter_date_to_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
            ],
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['submitted']},
        ),
    ]
