# Generated by Django 4.2.1 on 2023-06-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'Friends'},
        ),
    ]
